import { defineConfig } from "oxlint";

export default defineConfig({
  plugins: ["eslint", "typescript", "oxc", "react", "react-perf", "import"],
  categories: {
    correctness: "error",
    suspicious: "error",
    pedantic: "error",
    perf: "error",
    style: "error",
    restriction: "error",
  },
  rules: {
    "typescript/explicit-module-boundary-types": "off",
    "typescript/explicit-function-return-type": "off",
    "react/jsx-filename-extension": ["error", { extensions: [".tsx"] }],
    "react/react-in-jsx-scope": "off",
    "jsx-max-depth": "off",
    "sort-imports": "off",
    "no-ternary": "off",
    "sort-keys": "off",
    "strict-boolean-expressions": "off",
    "no-magic-numbers": "off",
    "max-statements": "off",
    "no-async-await": "off",
    "no-console": "off",
    "no-non-null-assertion": "off",
    "capitalized-comments": "off",
    "no-undefined": "off",
    "import/no-default-export": "error",
    "max-lines": "off",
    "import/no-named-export": "off",
    "import/no-unassigned-import": "off",
    "import/prefer-default-export": "off",
    "no-new-array-as-prop": "off",
    "no-inline-comments": "off",
    "func-style": [
      "error",
      "expression",
      {
        allowArrowFunctions: true,
      },
    ],
    "eslint/max-lines-per-function": "off",
    "react-perf/jsx-no-new-object-as-prop": "off",
    "no-optional-chaining": "off",
    "import/exports-last": "off",
    "typescript/consistent-type-definitions": ["error", "type"],
    "oxc/no-rest-spread-properties": "off",
    "eslint/id-length": "off",
    "import/consistent-type-specifier-style": "off",
    "import/max-dependencies": "off",
    "react/jsx-props-no-spreading": "off",
  },
  overrides: [
    {
      files: ["**/*.spec.ts", "**/*.spec.tsx", "**/*.fixture.tsx"],
      rules: {
        "no-console": "off",
        "func-style": "off",
        "no-thenable": "off",
        "no-empty-function": "off",
        "only-export-components": "off",
        "func-names": "off",
        "import/no-nodejs-modules": "off",
        "oxc/no-async-await": "off",
        "max-statements": "off",
      },
    },
    {
      files: ["**/*.config.ts", "**/*.config.mjs", "**/*.config.js"],
      rules: {
        "import/no-default-export": "off",
        "import/no-anonymous-default-export": "off",
        "import/no-nodejs-modules": "off",
      },
    },
    {
      files: ["**/+*.tsx", "**/+*.ts"],
      rules: {
        "import/no-default-export": "off",
        "react-hooks/rules-of-hooks": "off",
      },
    },
  ],
});
